version: '3.8'

services:
  my_shlink:
    image: shlinkio/shlink:stable
    container_name: my_shlink
    ports:
      - "8080:8080"
    environment:
      DEFAULT_DOMAIN: ${DEFAULT_DOMAIN}
      IS_HTTPS_ENABLED: ${IS_HTTPS_ENABLED}
      DB_DRIVER: ${DB_DRIVER}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      SHELL_VERBOSITY: ${SHELL_VERBOSITY}
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:latest
    volumes:
      - ./build/mysql/mysqld_charset.cnf:/etc/mysql/conf.d/my.cnf
      - ./var/lib/mysql:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

